// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: sync.proto

/* eslint-disable */

export const protobufPackage = "marad.sync.v1";

/**
 * Placeholder so proto:gen has something to compile. Real sync messages
 * (events, deltas, HLC tie-breaks, etc.) are defined in P0-6 (sync-engine).
 */
export interface Heartbeat {
  nodeId: string;
  hlc: string;
  sentAtUnixMs: string;
}
